env:
  matrix:
  - MYCONDAPY=2.7
  - MYCONDAPY=3.6
  global:
    # ANACONDA_TOKEN
    - secure: "j9gWsoi5KIJexLobwzyB8U8gWDRxvUgoEgQINevzCdc6tdNr2ZeVBM5Q7Xw5kCb2o0MvF4V7+xMLBOuvMjXS7dLMJ0Rnh2gCpojnXNzNzXpL/PaG7dTE+CKEDjSEzs2qNDsHGoFXx3lTrACm7Ol6Bl4OnppRpKUwJNDvJI0PUvJqNlBCZgecorzVm4ucvBcloFEmy7WF7WbRHBoTQrdujq4ziZ5c5F3vFWvNmHGQqU94FqroLBz05ie4gHgMaRip0l9TVOYEyw9qBEFHssPpux4yd0aijpvZnrS/ze4XvT8JkY9eGyU3M+OS7A+aq1wBC/lhZnx8M/Aygz3hfn2b8ZGGDsskGCrBKVjSwLzm+ZLb1tHugnYaI3WRYLFWK5+4cadVTgBTgkyJQMeX61lx/IwL3YcrhsBfneI/6vAu2DmGUoeiDhd4DpVq7Y+FBZ1F188HZpMmVlsFaTKrHJL/aUiEJd0d0ooN8cJbOJSCr4IlN5036cNUQsUu8Kwr6ncwifIq2sx0eM0dmUemP9hUYd069tW9gwapYt9E7aTlHQpxwdr8chS0vWsl+OZvdmiR0xD7vMHzaGtmG8YvSH7o7sr7z0DIxIKJBVzd93tgC1b9oZrySuSEQByZqsia9ZYBTCT3aJ2MfqbYXL6dZxpFnxrH8ntrBBh4KIdcZAzGTXU="
    # GITHUB_TOKEN
    - secure: "dG5ClYlMT/EADB7tdCsuM/8blSopvYu9CLCnKMtRasbeZ8EjuVIpq8v+p+vbeg7KFIuFqFuFjsfTKVOOWhzIYhNMvrsGpWl8HjVcDx4PhIooEix465efF99bFMQudd7FpZ1HHuNyXhsmrbx+xVdieEMfJVH5yX8e2dCQu01hbPEbCVzaFnez6iOOPcACqLaoZg7ofZ7F/mc2wJPMfzouGKotl7FhSsaoIJ3g0cwJ8BF4kxmM4J6WYjGV4MfGf3JTK8pUwkfqRPigpZITchT48sS6yT0qnCNHs6Nic/RHB0cJlHFRlA2Gpi7OafVIQXBPaQpLxidZ7oN6JH0ztfq/RYIfrCaGNWjd6G7PfPPJbtT5lQlRGF7FOX/U6syy7pzSe+sFiHmlEZKYKc6jW+xwCXYOXoPB0ikjC9HMjI2jyVCYZzAcfdJThDDYU0IdgNn99ejbmBXefzQMLJAZLf+JTbRpxjh93KM7Xv46pn8cirRaT3Sun/g2U24/K63NN8jJIuxrzSsH9EURSg27J9O65Z3M0r98ru9IGau4j9ge0FD+K/YiOiOSnm/mNkpmiuap5vhX0C5vT54QCgIPeP1ERRyuYI+V2tzIUSUYgGmOt/zX+QF2qBy0ZUiyDXgA9awhQupxEbbXsLA/XOuidV1ODxqob193dGFKLayhwsJR78M="
    # PYPI_PASSWD
    - secure: "Qh6JLMS4EklyRXNptUwim9ZcJvJxGfR0Lmd+W9tLaQ9d+c11wr376pZDzzbaGv7fM/tscWRYaCk8qVveSzGbLHi3Fy7NTFDIpXCpuV1ZSgCEyTmQLtoJPLK6fZc/iNOZdg5vk2QDn7Mk11xWoPwekagMsl0+IOAZu+JEGBw14pTrqMAXkLL7xI34dGfuJaOAQHo7GprU2bIgV0vcJIV3wgifo79ouZGVLWoS9iJkJ73coKji86LN/QV8PGqDp/aqNwdQCu0WUz1WuG6DBCQMtdohKROpu97HFhvdPICIM7d58Pyi1JBVrjSlKHw/Sz8ThCDPRBP2UZnjc5xn7IA5zuAeOLxaXbdxdLGMvKYa897+gNXRgMRTryVo4O/9IbkYIPGM2fHAarhyDzuTjyjIhG1fwi13iWz6ub02hrHWnXNJ6eGwXdtqS0o0uu4RZ1SrAxjYxrPNbLgq29Df/ywyYqJl0aZ2hAbswwUM6GQip4n3V/gkKjlDo6BSM4Ja/TyIOyq+m7u40NfYuRCkkKio3Khg//YUCySmLZ/7Cup7LSP++U/Cewd6ycWafj/y0yfSEo9x5UzK74ilq3UGK684NXlw8A9Cp1PZa+Y0Ka+M2ycE1L9c6d19F5VqeQqivces1lmG59Zv2EJ/CkSw9n/Oyg/3IrxZ06KpunpOwVRiwAk="
    - PYPKG=pycydemo
    - GITHUB_REPO_NAME=theochem/python-cython-ci-example

# Do not use Travis Python to save some time.
language: generic
os:
  - linux
  - osx
osx_image: xcode6.4
dist: trusty
sudo: false

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/

install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  else
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
- conda update -q conda
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
# Install conda tools for packaging and uploading
- conda install python=${MYCONDAPY} numpy cython sphinx conda-build anaconda-client
# Install more recent stuff with pip
- pip install codecov coverage pylint pycodestyle pydocstyle
# Show conda info for debugging
- conda info -a

# Install the latest cardboardlinter
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    pip install --upgrade git+https://github.com/theochem/cardboardlint.git@master#egg=cardboardlint;
  fi


script:
# Static linting
# --------------

- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    cardboardlinter --refspec $TRAVIS_BRANCH -f static;
  fi

# Testing with conda package
# --------------------------

# Build the conda package
- git fetch origin --tags
- conda build -q tools/conda.recipe
# Install Conda package
- conda install --use-local $PYPKG
# Run the unittests, using the installed package
- (cd; nosetests ${PYPKG} -v --detailed-errors)

# In-place building and testing
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# This is allows for coverage analysis and dynamic linting. The compiler settings used
# here are not suitable for releases, so we need to recompile and rerun the tests.

# Install GCC compilers for in-place builds, even on OSX because clang does not manage to
# compiler our C++ code.
- conda install gcc libgcc;

# Uninstall conda package, to be sure. The conda cpp package is still used.
- conda uninstall ${PYPKG}
- python setup.py build_ext -i --define CYTHON_TRACE_NOGIL
# Run nosetests without coverage.xml output. That file is broken by nosetests (pyx files
# not include) and gets priority over .coverage, which contains everything.
- coverage erase;
  nosetests ${PYPKG} -v --detailed-errors --with-coverage --cover-package=${PYPKG} --cover-tests --cover-inclusive --cover-branches;
  coverage xml -i
# Dynamic linting
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    cardboardlinter --refspec $TRAVIS_BRANCH -f 'dynamic';
  fi

# Some other stuff
# ----------------

# Build source package, should work too and needed for deployment to Github and
# PyPI.
- python setup.py sdist

# Compile documentation
- (cd doc; make html)

after_success:
# Upload the coverage analysis
- codecov -f ~/coverage.xml

before_deploy:
# Try to set some env vars to configure deployment
- export IS_PRERELEASE=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("true" if ("a" in tt or "b" in tt) else "false")')
- echo ${IS_PRERELEASE}
- export ANACONDA_LABEL=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("alpha" if ("a" in tt) else ("beta" if "b" in tt else "main"))')
- echo ${ANACONDA_LABEL}

# In deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
deploy:
- provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: ${IS_PRERELEASE}

- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload --force -l ${ANACONDA_LABEL} ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true

- provider: pypi
  skip_cleanup: true
  user: theochem
  password: ${PYPI_PASSWD}
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"

- provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  project_name: ${PYPKG}
  local_dir: doc/_build/html
  on:
    repo: ${GITHUB_REPO_NAME}
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
    tags: true
